### PR TITLE
kill multi_json  Dependencies

### PR DESCRIPTION
**Pull request by u2**
http://www.mikeperham.com/2016/02/09/kill-your-dependencies/

> Some software engineering rules:
> 
> No code runs faster than no code.
> No code has fewer bugs than no code.
> No code uses less memory than no code.
> No code is easier to understand than no code.
> Kill those dependencies. Your gems and apps will be better for it.

### CODE REVIEW

**Comment by rngtng** [comment]
epic thx :+1:  ;)

**Comment by dblock** [comment]
Same questions and issues around merging this as in https://github.com/ruby-grape/grape/pull/1274. Lets have a discussion there first?

**Comment by LeFnord** [comment]
@u2 … please can you rebase it

**Comment by dblock** [comment]
This is a non trivial change even though it looks trivial, it *will* break a bunch of people who use gems like oj, silently, so there be dragons!

**Comment by LeFnord** [comment]
saw the referenced discussion … though there was a decision 
and it seems, that @u2 removed its fork -> so should it be closed?

**Comment by dblock** [comment]
I stand by everything I said in the Grape issue: I'd love this, but with a way to reinstate backward compatibility for existing users. A change that just drops multi_json in favor of JSON prevents that.

**Comment by LeFnord** [comment]
though this https://github.com/ruby-grape/grape/pull/1274#issuecomment-184381824 was the decision, but yeah, it seems, nothings was done in this direction, so both PRs should be closed

**Comment by dblock** [comment]
Related, https://github.com/ruby-grape/grape/pull/1623.

**Pull request closed without merging**
