### PR TITLE
Provide Grape::Entity::Options#dig

### PR DESCRIPTION
**Pull request by kachick**

### CODE REVIEW

**Comment by LeFnord** [comment]
thanks @kachick … will mörge it after #278

**Comment by kachick** [comment]
Ah... ruby provide `Hash#dig` since 2.3... So can I quote the rspecs in 2.2.x ?

  https://github.com/ruby-grape/grape-entity/blob/030d02e6cc30c621b10f068ed120cfcb11d80842/.travis.yml#L18

  it does not mean regression.

**Comment by kachick** [comment]
Thank you! 🙇

**Comment by yuya-takeyama** [comment]
@LeFnord 
Hi, is there any plan to release this change as a new version?

**Comment by LeFnord** [comment]
yeap, there is a plan … will do it after the new ruby is out → in the next days :)

**Comment by kechol** [comment]
Hi @LeFnord !
I's been a while after Ruby v2.5.0 has been released. Do you have any plan to release a new version for grape-entity? I saw you've already worked for ruby 2.5 at https://github.com/ruby-grape/grape-entity/pull/287 , but if you have any concerns or obstacles, I'd grad to hear that. Thanks!

**Comment by LeFnord** [comment]
release 0.7.0 is out … thanks again 😄

**Comment by yuya-takeyama** [comment]
Thank you @LeFnord, now I'm trying to update the gem in our products.
I really appreciate your work!

**Pull request merged**
