### PR TITLE
Be able to use format_with safely

### PR DESCRIPTION
**Pull request by epaulet**
I don't have any proposed solution for this, but this is in response to https://github.com/ruby-grape/grape-entity/issues/131

Currently, `safe: true` does not do anything when used together with `format_with`. Before 0.4.6, it would just return a nil value if a method did not exist. As of 0.4.6, there is a NoMethodError instead.

### CODE REVIEW

**Comment by marshall-lee** [comment]
Thanks, will look at this soon.

**Comment by marshall-lee** [comment]
This spec fails on `0.4.5` too but for different reason.

**Comment by marshall-lee** [comment]
```
     Failure/Error: expect(res).to have_key :timestamp
       expected #has_key?(:timestamp) to return true, got false
```

**Comment by marshall-lee** [comment]
So `0.4.5` doesn't return `nil` value as you mentioned. It simply doesn't expose your attribute at all.

**Comment by marshall-lee** [comment]
...but i agree it's some kind of bug that affects only `Hash` objects. I will fix it soon on both `0-4` and `master`.

**Comment by epaulet** [comment]
@marshall-lee I added some more to this to be more clear about the issue I'm having.

This is the type of behavior I was seeing in previous versions (0.4.5) where a nil value wasn't passed into a formatters when `safe: true` was passed in as an option. This issue still was not resolved with a7d6df4e51dd4ef9515a31d935810e8bd29e18a0

**Comment by marshall-lee** [comment]
@epaulet thanks, will review soon.

**Comment by epaulet** [comment]
The `safe` flag seems to be for exposing `nil` if the entity doesn't have the correct attribute. The intention here is to ignore the attribute altogether if it resolves to nil. Perhaps an `allow_nil` flag would be more appropriate. Either way, going to close this PR for now since the solution seems like the wrong one...

**Pull request closed without merging**
