### PR TITLE
implement universally unique attributes to silo exposure logic

### PR DESCRIPTION
**Pull request by wyattisimo**
Here's my first stab at issue #52. It silos exposure logic by creating a universally unique attribute for each exposure.

It allows for stuff like this to work properly:

```ruby
expose :name, if: { greeting: :formal } do |obj, opts|
  "#{obj.title} #{obj.first_name} #{obj.last_name}"
end

expose :name, if: { greeting: :friendly } do |obj, opts|
  "#{obj.nick_name}"
end
```

This ended up requiring more tweaking than I expected. I also had to modify a number of specs that are accessing certain protected methods that now require a unique attribute (like `value_for`).

I added [specs to test applying "if" conditions to an attribute in separate exposure declarations](https://github.com/wyattisimo/grape-entity/blob/master/spec/grape_entity/entity_spec.rb#L23-L59), and all existing specs are currently passing, but there are likely some new use cases and/or side effects that need to be discussed/resolved.

**EDIT**

Just for clarification... using the above exposure declarations, grape-entity currently produces the following exposures hash:

```ruby
{
  name: {
    if: { greeting: :friendly },
    proc: #<Proc2>
  }
}
```

With this update, those same exposure declarations will result in an exposures hash like this:

```ruby
{
  name___939828ec686b4a6cb9f86ddbe38439a3: {
    if: { greeting: :formal },
    proc: #<Proc1>
  },
  name___b93f9ab39e4c4b67a6aa192cd7f49dbf: {
    if: { greeting: :friendly },
    proc: #<Proc2>
  }
}
```

### CODE REVIEW

**Comment by wyattisimo** [comment]
@dblock finally had time to get back to this. implemented array of exposures for each attribute. all tests are passing.

**Comment by wyattisimo** [comment]
@dblock okay, upstream conflicts should be resolved. let me know what you think.

i'll squash and update README and CHANGELOG once it's finalized

**Comment by dblock** [comment]
This looks good to me, squash/rebase/etc.?

**Comment by u2** [comment]
What's going on?

**Comment by dblock** [comment]
There're quite a few merge conflicts that need to be looked at carefully, bump @wyattisimo.

**Comment by wyattisimo** [comment]
Sorry for the delay! Been busy with other things and stuff and things... I'll try to get this wrapped up in the next few days.

**Comment by u2** [comment]
Maybe I can help to squash these commits, there are quite a few merge conflicts and need to change something for the new commits.

**Comment by marshall-lee** [comment]
@wyattisimo, @u2 

Hi! Please look at the work done in #151 — it solves this problem differently and without performance degradation. It's not released yet and will go to 0.5.0 but you can try it out from current master.

**Pull request closed without merging**
